### PR TITLE
add json parser

### PR DESCRIPTION
**Pull request by archaistvolts**
Thanks for sharing this project :+1:. I found it pretty well documented and nice to use.

This patch adds a working json parser which parses into a `std.json.Value`.

The parser has the following results from [JSONTestSuite](https://github.com/nst/JSONTestSuite).  You can see there are only 3 failures (yellow lines at bottom) out of around 373 json files.

Screenshot-10

Screenshot-9

### CODE REVIEW

**Comment by PiIsRational** [comment]
Cool, Thanks! I'll try to find what causes the problem.

**Comment by archaistvolts** [comment]
I think the character production is slightly too lenient, allowing raw newlines and tabs in strings.

**Comment by archaistvolts** [comment]
this fixes it.  with this, there are no more failures.  sorry i should have fixed this first.  you can apply if you want or i can make another pr.  let me know.
```diff
diff --git a/test/json/grammar.peg b/test/json/grammar.peg
index 7501338..dbd1735 100644
--- a/test/json/grammar.peg
+++ b/test/json/grammar.peg
@@ -97,7 +97,7 @@ string: "json.Value" = '"' character* '"' {
   ;
 
 character = 
-    !["\\] .
+    !["\\\n\t] .
   | '\\' escape
   ;
 
```

**Comment by PiIsRational** [comment]
finally i chose to disallow all bytes smaller than `x20` which did fix it. 
i also  did dome changes to the grammar, such that it returns the `json.Value` on pass (and added it to the example grammars).

**Comment by PiIsRational** [comment]
Oh and I forgot to write the trick for forcing the parser to parse a full file at once: just add !. at the end of the grammar, 
that way no need to test for it.

**Comment by archaistvolts** [comment]
> Oh and I forgot to write the trick for forcing the parser to parse a full file at once: just add !. at the end of the grammar,

Thanks. Didn't know about this.

> finally i chose to disallow all bytes smaller than x20 which did fix it.

That seems better, closer to what [the spec](https://www.json.org/json-en.html) says anyway.

> character
>     '0020' . '10FFFF' - '"' - '\'
>     '\' escape

**Comment by archaistvolts** [comment]
Looks like the json changes resulted in some problems. Just pulled and I get this:

```console
~/.../zig/zapp $ zig build test
test
└─ run test
   └─ zig test Debug native 1 errors
.zig-cache/o/4a0e4b0d601628ff113ef76b24354dd5/test/json/json.zig:5:33: error: expected type expression, found '%'
const assert = std.debug.assert;
                                ^
```

This fixes the above
```diff
diff --git a/test/json/grammar.peg b/test/json/grammar.peg
index b94d4da..f2d452a 100644
--- a/test/json/grammar.peg
+++ b/test/json/grammar.peg
@@ -10,6 +10,9 @@ fn parseInt(s: []const u8) json.Value {
 }
 %%
 
+%% FIELDS
+%%
+
 json: "json.Value" = element FileEnd { $1 };
 
 element: "json.Value" = ws value ws { $2 };
```

But that leads to a new error:
```console
~/.../zig/zapp $ zig build test
test
└─ run test
   └─ zig test Debug native 1 errors
test/json/main.zig:12:26: error: expected type '@typeInfo(@typeInfo(@TypeOf(main.parse)).Fn.return_type.?).ErrorUnion.error_set!json.Json(.{ .use_memo = true, .stack_limit = null })', found 'json.dynamic.Value'
        .pass => |value| value,
                         ^~~~~
```

**Comment by archaistvolts** [comment]
Ah i see what the issue is. Working on a PR.

**Pull request merged**
